name: Build

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python }}

      - name: Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake ninja-build \
            pybind11-dev \
            libopenblas-dev liblapack-dev \
            libeigen3-dev libsleef-dev

      - name: macOS deps
        if: runner.os == 'macOS'
        run: |
          brew install cmake ninja openblas eigen pybind11

#      - name: Windows deps
#        if: runner.os == 'Windows'
#        run: |
#          choco install cmake ninja -y

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==2.0.1


      - name: Install Python deps
        run: python -m poetry install --no-interaction --no-ansi

      - name: Configure
        shell: bash
        run: |
          PYTHON_EXECUTABLE=$(python -m poetry run python - <<EOF
          import sys
          print(sys.executable)
          EOF
          )

          echo "Using Python: $PYTHON_EXECUTABLE"

          cmake --preset dev \
            -DPython_EXECUTABLE="$PYTHON_EXECUTABLE" \
            -DPython3_EXECUTABLE="$PYTHON_EXECUTABLE"

      - name: Build
        run: cmake --build --preset dev -j2

      - name: Import smoke test
        run: |
          poetry run python - <<EOF
          from nova.src.backend.core import Tensor
          x = Tensor([1.0, 2.0])
          y = x + x
          print(y)
          EOF

      - uses: actions/upload-artifact@v4
        with:
          name: nova-build-${{ inputs.os }}
          path: nova/src/backend/core/clib
